spring:
  application:
    name: docs-client

  datasource:
    url: jdbc:derby:memory:users;create=true
    initialization-mode: embedded

  jpa:
    generate-ddl: false
    database: default
    properties:
      hibernate:
        hbm2ddl:
          auto: update

    hibernate:
      ddl-auto: update

server:
  port: 8082
