spring:
  application:
    name: docs-client

  datasource:
    url: jdbc:derby:memory:users;create=true
    initialization-mode: embedded

  jpa:
    generate-ddl: false
    database: default
    properties:
      hibernate:
        hbm2ddl:
          auto: update

    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082
  ssl:
    enabled: false
    key-store: classpath:pki/client.jks
    key-store-password: 123456
    key-alias: client
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:pki/client.jks
    trust-store-password: 123456
    trust-store-type: JKS
