spring:
  application:
    name: docs-server

  datasource:
    url: jdbc:derby:memory:docs;create=true
    initialization-mode: embedded

  jpa:
    generate-ddl: false
    database: default
    properties:
      hibernate:
        hbm2ddl:
          auto: update

    hibernate:
      ddl-auto: update

server:
  port: 8081
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:pki/server.jks
    key-store-password: 123456
    key-alias: server
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:pki/server.jks
    trust-store-password: 123456
    trust-store-type: JKS

